## Notebook with Numpy & Pandas Code

#### Numpy Essentials

In [1]:
import numpy as np

In [4]:
# np array
np.array([1,3,5.5,6,7])

# np multidimensional array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Create an array from 1st to 2nd number in 3th number steps
np.arange(5, 20, 4)

# Create an array of 1 of shape 3x4
np.zeros((3,4))

# Create an array of 1 of shape 3x4
np.ones((3,4))

# Create an empty array of shape 3x4
np.empty((3,4))

# Create a 2x2 identity matrix
np.eye(2)

# Create a array with random values of shape 2x2
np.random.random((2,2))


array([[0.37772664, 0.87448761],
       [0.32060394, 0.37647756]])

In [11]:
# Shape & dimensions of an array

a = np.random.rand(10,10)
print(a.shape)
print(a.ndim)
a

(10, 10)
2


array([[0.31590093, 0.88296248, 0.29834076, 0.47792088, 0.22021277,
        0.43083243, 0.32332773, 0.6014744 , 0.83954072, 0.53469504],
       [0.98661368, 0.72050014, 0.94183973, 0.60984815, 0.75309968,
        0.43084193, 0.73379182, 0.04383821, 0.32194236, 0.31764994],
       [0.86911461, 0.33706378, 0.43637506, 0.25265759, 0.85325715,
        0.08853235, 0.39228383, 0.67986702, 0.92591115, 0.19810425],
       [0.09818502, 0.10006327, 0.57123041, 0.97770748, 0.74566653,
        0.26936626, 0.92461425, 0.45842707, 0.24790842, 0.34789535],
       [0.91932628, 0.53824107, 0.43571816, 0.85022889, 0.5157165 ,
        0.57166482, 0.25167209, 0.93203174, 0.29826231, 0.77231623],
       [0.56276014, 0.12381335, 0.36964946, 0.61692354, 0.37512099,
        0.60294626, 0.58877438, 0.69823059, 0.00558368, 0.15525977],
       [0.14991943, 0.09476348, 0.03134874, 0.63396863, 0.90299208,
        0.79841272, 0.94502831, 0.89007335, 0.62127216, 0.30240407],
       [0.54129982, 0.32665266, 0.4974514